#!/bin/bash

co="echo 'conf'"
v="echo 'interface vl 1'"
x="echo 'exit'"
route="echo 'ip route 172.16.0.0 255.255.0.0 172.16.1.3'"
route2="echo 'ip route 172.16.0.0 255.255.0.0 172.10.1.65 metric 60'"
nom=81

echo 'Eltex'
diap=(78 79 80 81 82 83 84 85)
#diap=(74)
for b in ${diap[@]}; do
  a="-tt admin@172.16.1.$b"
#  a2="-tt admin@172.10.1.$nom"
#  new="-tt admin@172.16.1.$nom"
  # Подключиться, добавить маршруты, 1) добавить IP из другой маски, 2) добавить IP из нужной маски, 3) удалить промежуточный IP:
#  echo "CHANGING 172.16.4.$b ---> 172.16.1.$nom"
#  { sleep 3 ; eval $co ; sleep 1 ; eval $route ; sleep 1 ; eval $route2 ; sleep 3 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.$nom /24" ; sleep 3 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh $a

#  { sleep 3 ; eval $co ; sleep 1 ; eval $route ; sleep 1 ; eval $route2 ; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.10.1.$nom /24" ; sleep 3 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh $a
#  { sleep 3 ; eval $co ; sleep 1 ; eval $v ; sleep 1 ; echo "no ip address 172.16.3.$b" ; sleep 1 ; echo "ip address 172.16.1.$nom /24" ; sleep 3 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh $a2
#  { sleep 3 ; eval $co ; sleep 1 ; eval $v ; sleep 1 ; echo "no ip address 172.10.1.$nom" ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; echo "write" ; sleep 1 ; echo "y"; sleep 5 ; eval $x ; } | ssh $new
  { sleep 5 ; eval $co ; sleep 1 ; eval $route ; sleep 1 ; eval $x ; sleep 1 ; echo "write" ; sleep 1 ; echo "y"; sleep 5 ; eval $x ; } | ssh $a
#  if (( nom != 80 )) ; then
#    nom=$((nom+1))
#  else
#    nom=$((nom+4))
#  fi
done