#!/bin/bash
co="echo 'conf'"
v="echo 'interface vl 1'"
x="echo 'exit'"
#routeway="echo 'ip default-gateway 172.16.1.3'"
route="echo 'ip route 172.16.0.0 255.255.0.0 172.16.1.3'"
#route2="echo 'ip route 172.16.0.0 255.255.0.0 172.10.1.65 metric 60'"
nom=100

echo 'SNR'
diap=(13	14	15	16	17	18	3	4	5	6	7	8	9)
#diap=(74)
for b in ${diap[@]}; do
  a="-tt admin@172.16.3.$b"
#  a2="-tt admin@172.10.1.$nom"
#  new="-tt admin@172.16.1.$nom"
  # Подключиться, добавить маршруты, 1) добавить IP из другой маски, 2) добавить IP из нужной маски, 3) удалить промежуточный IP:
  echo "CHANGING 172.16.3.$b ---> 172.16.1.$nom"
  { sleep 3 ; eval $co ; sleep 1 ; eval $route ; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.$nom 255.255.255.0" ; sleep 2 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; echo "write" ; sleep 1 ; echo "y"; sleep 5 ; eval $x ; } | ssh $a
  nom=$((nom+1))
done


/usr/bin/expect<<EOF
spawn ssh -tt admin@172.16.1.20
expect "password:"  send "Angel1@$\n"
expect "#"          send "conf\n"
expect "#"          send "conf\n"
expect "#"          send "exit\n"
expect "#"          send "exit\n"
EOF
/usr/bin/expect<<EOF
spawn ssh -tt admin@172.16.1.25
expect "password:"  send "Angel1@$\n"
expect "#"          send "show clock\n"
expect "#"          send "exit\n"
EOF