#!/usr/bin/expect
#
set nom 113
#foreach b {14	15	16	17	18	3	4	5	6	7	8	9} {
#  spawn ssh admin@172.16.3.$b
#  expect "#" { send "conf\n" }
#  expect "#" { send "ip route 172.16.0.0 255.255.0.0 172.16.1.3\n" }
#  expect "#" { send "interface vl 1\n" }
#  expect "#" { send "ip address 172.16.1.$nom 255.255.255.0"}
#  expect "#" { send "exit\n" }
#  expect "#" { send "exit\n" }
#  expect ":" { send "y\n" }
#  expect "#" { send "exit\n"}
#  puts "\n"
#  incr nom
#  }

foreach b {20 25} {
  spawn ssh admin@172.16.1.$b
  expect "d:" { send "Angel1@$\n" }
  expect "#" { send "conf\n" }
  expect "#" { send "ip route 172.16.0.0 255.255.0.0 172.16.1.3\n" }
  expect "#" { send "interface vl 1\n" }
  expect "#" { send "ip address 172.16.1.$nom 255.255.255.0"}
  expect "#" { send "exit\n" }
  expect "#" { send "exit\n" }
  expect ":" { send "y\n" }
  expect "#" { send "exit\n"}
  puts "\n"
  incr nom
  }
