#!/bin/bash
#komanda=(5 8 8 4)
#let nomer=1
#for i in ${komanda[@]}; do
#  echo "$nomer $i"
#  let nomer=nomer+1
#done

#diap=(1	6	73	74 78	79	80	82	83	84	85	86)
#for i in ${diap[@]}; do
for i in {100..114} ; do
  ping -w 2 172.16.1.$i
done

#nom=61
#newIP=()
#echo 'Cisco IP from 61 to 86'
#diap=(1	6	73	74 78	79	80	82	83	84	85	86)
#for b in ${diap[@]}; do
#  newIP=(${newIP[@]} "$nom")
#  nom=$((nom+2))
#done
#for value in "${newIP[@]}"
#do
#     echo $value
#done


#echo 'Cisco IP 89'
#echo "172.16.1.$nom"
