#!/bin/bash

co="echo 'conf'"
#v="echo 'interface vl 1'"
x="echo 'exit'"
route="echo 'ip route 172.16.0.0 255.255.0.0 172.16.1.3 metric 30'"
route2="echo 'ip route 172.16.0.0 255.255.0.0 172.10.1.65 metric 60'"
nom=78

echo 'Cisco'
diap=(2 7 8 9 10)
#diap=(74)
for b in ${diap[@]}; do
  a="-tt -c aes256-ctr -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1 admin@172.16.1.$b"
  a2="-tt -c aes256-ctr -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1 admin@172.10.1.$nom"
  new="-tt -c aes256-ctr -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1 admin@172.16.1.$nom"
  # Подключиться, добавить маршруты, 1) добавить IP из другой маски, 2) добавить IP из нужной маски, 3) удалить промежуточный IP:
#  { sleep 2 ; eval $co ; sleep 1 ; eval $route ; sleep 1 ; eval $route2 ; sleep 3 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.$nom /24" ; sleep 2 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh $a
  { sleep 2 ; eval $co ; sleep 1 ; eval $route ; sleep 1 ; eval $route2 ; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.10.1.$nom /24" ; sleep 2 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh $a
  { sleep 2 ; eval $co ; sleep 1 ; eval $v ; sleep 1 ; echo "no ip address 172.16.1.$b" ; sleep 1 ; echo "ip address 172.16.1.$nom /24" ; sleep 2 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh $a2
  { sleep 2 ; eval $co ; sleep 1 ; eval $v ; sleep 1 ; echo "no ip address 172.10.1.$nom" ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; echo "write" ; sleep 1 ; echo "y"; sleep 5 ; eval $x ; } | ssh $new
#  { sleep 5 ; eval $co ; sleep 1 ; eval $route ; sleep 1 ; eval $x ; sleep 1 ; echo "write" ; sleep 1 ; echo "y"; sleep 5 ; eval $x ; } | ssh $a
  nom=$((nom+1))
done