#!/bin/bash

co="echo 'sys'"
v="echo 'interface vl 1'"
x="echo 'exit'"
route="echo 'ip route 172.16.0.0 255.255.0.0 172.16.1.3'"
nom=86

echo 'Huawei'
diap=(21 22 23 24 25 11 12)
#diap=(74)
for b in ${diap[@]}; do
  a="-tt admin@172.16.1.$b"
  # Подключиться, добавить маршруты, изменить IP
  echo "CHANGING 172.16.4.$b ---> 172.16.1.$nom"
  { sleep 12 ; eval $co ; sleep 1 ; eval $route ; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.$nom /24" ; sleep 3 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; echo "save" ; sleep 1 ; echo "y"; sleep 5 ; eval $x ; } | ssh $a

#  { sleep 5 ; eval $co ; sleep 1 ; eval $route ; sleep 1 ; eval $x ; sleep 1 ; echo "write" ; sleep 1 ; echo "y"; sleep 5 ; eval $x ; } | ssh $a
#  if (( nom != 80 )) ; then
#    nom=$((nom+1 or     ))
#  else
#    nom=$((nom+4))
#  fi
done