#!/usr/bin/expect

#Коммутаторы Cisco, Eltex
for {set b 61} {$b <= 85} {incr b} {
  spawn ssh admin@172.16.1.$b
  expect "#" { send "conf\n" }
  expect "#" { send "no ip telnet server\n" }
  expect "#" { send "exit\n"}
  expect "#" { send "write\n" }
  expect ")" { send "y\n" }
  expect "#" { send "exit\n"}
  puts "\n"
  }

foreach c {39 43 44 48 49 50 58} {
  spawn ssh admin@172.16.1.$c
  expect "#" { send "conf\n" }
  expect "#" { send "no ip telnet server\n" }
  expect "#" { send "exit\n"}
  expect "#" { send "write\n" }
  expect ")" { send "y\n" }
  expect "#" { send "exit\n"}
  puts "\n"
  }