#!/bin/bash

co="echo 'sys'"
v="echo 'interface vl 1'"
x="echo 'quit'"
route="echo 'ip route-static 172.16.0.0 16 172.16.1.3'"
nom=96

echo 'Huawei'
#diap=(86..99)
diap=(96)
for b in ${diap[@]}; do
  a="-tt admin@172.16.1.$b"
#  # Подключиться, добавить маршруты, изменить IP
#  echo "CHANGING 172.16.4.$b ---> 172.16.1.$nom"
#  { sleep 15 ; eval $co ; sleep 1 ; eval $route ; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.$nom 24" ; } | ssh $a &
#  sleep 20
#  PID=$!
#  echo "      $PID"
#  sleep 2
#  kill $PID
echo "connect to 172.16.1.$nom"
  { sleep 15 ; echo "save" ; sleep 1 ; echo "y"; sleep 5 ; eval $x ; } | ssh $a

#  if ((nom != 89)) ; then
#    nom=$((nom+1))
#  else
#    nom=$((nom+2))
#  fi
done