#!/usr/bin/expect
#Коммутаторы Huawei 3 86 87 88 89 91 92 93 94 95 96 97 98 99


# 94 и 96 сбивают скрипт!!!!!!!!!!!!!!!!


foreach b {3 86 87 88 89 91 92 93 95 97 98 99} {
  spawn ssh admin@172.16.1.$b
  expect ">" { send "sys\n" }
  puts "\n"
  expect ">" { send "sys\n" }
  expect "]" { send "undo telnet server enable\n" }
  expect "]" { send "y\n" }
  expect "]" { send "quit\n"}
  expect ">" { send "save\n" }
  expect "]" { send "y\n" }
  expect ">" { send "quit\n"}
  puts "\n"
  }