#!/usr/bin/expect

#set nom 53
#Основная масса SNR
foreach b {100 101 102 103 104 105 106 107 108 109 53 54 55} {
  spawn ssh admin@172.16.1.$b
  expect "#" { send "conf\n" }
  expect "#" { send "snmp-server securityip disable\n" }
  expect "#" { send "snmp-server enable traps\n" }
  expect "#" { send "exit\n"}
  expect "#" { send "write\n" }
  expect ":" { send "y\n" }
  expect "#" { send "exit\n"}
  puts "\n"
  }

#SNR без ключа SSH
foreach b {56 57} {
  spawn ssh admin@172.16.1.$b
  expect "d:" { send "Angel1@$\n" }
  expect "#" { send "conf\n" }
  expect "#" { send "snmp-server securityip disable\n" }
  expect "#" { send "snmp-server enable traps\n" }
  expect "#" { send "exit\n"}
  expect "#" { send "write\n" }
  expect ":" { send "y\n" }
  expect "#" { send "exit\n"}
  puts "\n"
  }

#SNR в сети Perco
spawn ssh admin@192.168.222.100
expect "#" { send "conf\n" }
expect "#" { send "snmp-server securityip disable\n" }
expect "#" { send "snmp-server enable traps\n" }
expect "#" { send "exit\n"}
expect "#" { send "write\n" }
expect ":" { send "y\n" }
expect "#" { send "exit\n"}
puts "\n"


#for {set b 100} {$b <= 114} {incr b} {
#  spawn ssh admin@172.16.1.$b
#  expect "d:" { send "Angel1@$\n" }
#  expect "#" { send "save\n" }
#  expect ":" { send "y\n" }
#  expect "#" { send "exit\n"}
#  }

