#!/bin/bash
#komanda=(5 8 8 4)
#let nomer=1
#for i in ${komanda[@]}; do
#  echo "$nomer $i"
#  let nomer=nomer+1
#done

diap=(SW-CB353B	SW-CB221	SW-S1-CLN	SW-CB331	SW-CB332	SW-CB33	SW-CB352	SW-CB551	SW-CB311	SW-CB541	SW-CB531	SW-CB411	SW-CB532	SW-CB431	SW-CB353A	SW-CB351A	SW-CB351B	SW-CB351C	SW-CB342B	SW-CB341B	SW-CB342A	SWT-CB341B	SWT-CB342A	SWT-CB342B	SW-CB322	SW-CB341A	SWT-CB321	SWT-CB322	SWT-CB323	SWT-CB351	SWT-CB341A	Gateway	SWT-CB231	SWT-CB222	SW-CB323A	SW-CB323B	SW-CB222	SW-CB231	SW-CB321	SW-CB211	SWT-CB211	SWT-CB353	SWT-CB352	SWT-CB221	SWT-CB521	SWT-CB24	SWT-CB311	SWT-CB511	SWT-CB412	SWT-CB431	SWT-CB532	SWT-CB411	SWT-CB541	SW-OPTIC1	SW-OPTIC2	SW-serv-perco)
for i in ${diap[@]}; do
#for i in {53..57} ; do
  ping -w 2 $i
done

#nom=61
#newIP=()
#echo 'Cisco IP from 61 to 86'
#diap=(1	6	73	74 78	79	80	82	83	84	85	86)
#for b in ${diap[@]}; do
#  newIP=(${newIP[@]} "$nom")
#  nom=$((nom+2))
#done
#for value in "${newIP[@]}"
#do
#     echo $value
#done


#echo 'Cisco IP 89'
#echo "172.16.1.$nom"
