#!/usr/bin/expect

#set nom 53
#для тестов
#spawn ssh admin@172.16.1.94
#expect "#" { send "show ports secur | include Dis\n" }
#interact



#set nom 53
#для тестов Gateway	SWT-CB231	SWT-CB222	SW-CB323A	SW-CB323B	SW-CB222	SW-CB231	SW-CB321	SW-CB211
foreach b {SW-CB353B	SW-CB221	SW-S1-CLN	SW-CB331	SW-CB332	SW-CB33	SW-CB352	SW-CB551	SW-CB311	SW-CB541	SW-CB531	SW-CB411	SW-CB532	SW-CB431	SW-CB353A	SW-CB351A	SW-CB351B	SW-CB351C	SW-CB342B	SW-CB341B	SW-CB342A	SWT-CB341B	SWT-CB342A	SWT-CB342B	SW-CB322	SW-CB341A	SWT-CB321	SWT-CB322	SWT-CB323	SWT-CB351	SWT-CB341A		SWT-CB211	SWT-CB353	SWT-CB352	SWT-CB221	SWT-CB521	SWT-CB24	SWT-CB311	SWT-CB511	SWT-CB412	SWT-CB431	SWT-CB532	SWT-CB411	SWT-CB541	} {
  spawn ssh admin@$b
#  expect "#" { send "conf\n" }
#  expect "#" { send "snmp-server enable\n" }
#  expect "#" { send "snmp-server community ro 0 public01\n" }
#  expect "#" { send "snmp-server community rw 0 private01\n"}
#  expect "#" { send "snmp-server host 172.16.1.5 v2c public01\n" }
#  expect "#" { send "exit\n"}
#  expect "#" { send "write\n" }
#  expect ":" { send "y\n" }
  expect "#" { send "exit\n"}
  puts "\n"
  }

#set nom 53
#для тестов
#foreach b {100 101 102 103 104 105 106 107 108 109 53 54 55} {
#  spawn ssh admin@172.16.1.$b
#  expect "#" { send "conf\n" }
#  expect "#" { send "snmp-server enable\n" }
#  expect "#" { send "snmp-server community ro 0 public01\n" }
#  expect "#" { send "snmp-server community rw 0 private01\n"}
#  expect "#" { send "snmp-server host 172.16.1.5 v2c public01\n" }
#  expect "#" { send "exit\n"}
#  expect "#" { send "write\n" }
#  expect ":" { send "y\n" }
#  expect "#" { send "exit\n"}
#  puts "\n"
#  }